In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("K12/NetworkRegulatorGene.tsv", sep="\t", skiprows=24)

In [9]:
df.head(2)

,1)regulatorId,2)regulatorName,3)RegulatorGeneName,4)regulatedId,5)regulatedName,6)function,7)confidenceLevel
0,RDBECOLICNC00063,ppGpp,NaN,RDBECOLIGNC00006,hisM,-,W
1,RDBECOLICNC00063,ppGpp,NaN,RDBECOLIGNC00030,agp,+,W

In [30]:
dict_TF = {}

for i in range(len(df["5)regulatedName"])):
    if df["5)regulatedName"][i] not in dict_TF.keys():
        L = []
        L2 = []
        L2.append(df["1)regulatorId"][i])
        L2.append(df["2)regulatorName"][i])
        L2.append(df["6)function"][i])
        L2.append(df["7)confidenceLevel "][i])
        L.append(L2)
        dict_TF[df["5)regulatedName"][i]] = L
    else:
        L = []
        L.append(df["1)regulatorId"][i])
        L.append(df["2)regulatorName"][i])
        L.append(df["6)function"][i])
        L.append(df["7)confidenceLevel "][i])
        dict_TF[df["5)regulatedName"][i]].append(L)

In [26]:
len(dict_TF.keys())

2743

# Load promoters dataset

In [27]:
df_promoters = pd.read_csv("dataframes/8_regulonDB_parsed_and_checked_locusTag.csv")

In [28]:
df_promoters.head()

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,Promoter -35 box start,Promoter -35 box end,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced,locus tag
0,RDBECOLIOPC00001,ispDF,reverse,RDBECOLITUC01454,ispDF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,1097710.0,1097715.0,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT,b1032
2,RDBECOLIOPC00003,ybjS,reverse,RDBECOLITUC00341,ybjS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RDBECOLIOPC00004,insJ,forward,RDBECOLITUC01510,insJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RDBECOLIOPC00005,murJ,forward,RDBECOLITUC00397,murJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
def search_regulator(gene, dict):
    activator = False
    repressor = False
    if gene in dict.keys():
        for elem in dict[gene]:
            if elem[2] == "+":
                activator = True
            if elem[2] == "-":
                repressor = True
    return activator, repressor

In [38]:
for i, row in df_promoters.iterrows():
    activator, repressor = search_regulator(row["TU first gene"], dict_TF)
    df_promoters.at[i, "activator"] = 1 if activator else 0
    df_promoters.at[i, "repressor"] = 1 if repressor else 0

In [39]:
df_promoters

,Operon ID,Operon name,Operon strand,TU ID,TU name,TU first gene,Promoter ID,Promoter name,Sigma factor,Promoter sequence,...,Promoter -35 box sequence,Promoter -10 box start,Promoter -10 box end,Promoter -10 box sequence,Promoter confidence,spacer,promoter sequence reduced,locus tag,activator,repressor
0,RDBECOLIOPC00001,ispDF,reverse,RDBECOLITUC01454,ispDF,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,RDBECOLIOPC00002,serX,reverse,RDBECOLITUC03528,serX,serX,RDBECOLIPMC03869,serXp,sigma70,gcgattttttcaaaaagtttgttgacctcaggtcatgatttcccta...,...,TTGACC,1097687.0,1097692.0,TAAATT,W,TCAGGTCATGATTTCCC,TTGACCTCAGGTCATGATTTCCCTAAATT,b1032,1.0,0.0
2,RDBECOLIOPC00003,ybjS,reverse,RDBECOLITUC00341,ybjS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,RDBECOLIOPC00004,insJ,forward,RDBECOLITUC01510,insJ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,RDBECOLIOPC00005,murJ,forward,RDBECOLITUC00397,murJ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3710,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02233,pstSCA,pstS,RDBECOLIPMC02666,pstSp2,sigma38,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,...,CATATA,3911576.0,3911586.0,TGTCCTATTTT,S,ACTGTCACCTGTT,CATATAACTGTCACCTGTTTGTCCTATTTT,b3728,1.0,1.0
3711,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02234,pstS,pstS,RDBECOLIPMC02666,pstSp2,sigma38,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,...,CATATA,3911576.0,3911586.0,TGTCCTATTTT,S,ACTGTCACCTGTT,CATATAACTGTCACCTGTTTGTCCTATTTT,b3728,1.0,1.0
3712,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02235,pstSCAB-phoU,pstS,RDBECOLIPMC02666,pstSp2,sigma38,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,...,CATATA,3911576.0,3911586.0,TGTCCTATTTT,S,ACTGTCACCTGTT,CATATAACTGTCACCTGTTTGTCCTATTTT,b3728,1.0,1.0
3713,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC02258,pstB-phoU,pstB,RDBECOLIPMC02689,pstBp2,sigma38,ttaccctgtgcgtactgctgctgaacattctggcgcgcgttgtttt...,...,CTGGCG,3908561.0,3908571.0,TTGCGAAGAAT,S,CGCGTTGTTT,CTGGCGCGCGTTGTTTTTGCGAAGAAT,b3725,1.0,1.0
3714,RDBECOLIOPC03559,pstSCAB-phoU,reverse,RDBECOLITUC03237,pstSCAB-phoU,pstS,RDBECOLIPMC03521,pstSp,sigma70,tcataaaactgtcatattccttacatataactgtcacctgtttgtc...,...,TTACAT,3911576.0,3911581.0,TATTTT,S,ATAACTGTCACCTGTTTGTCC,TTACATATAACTGTCACCTGTTTGTCCTATTTT,b3728,1.0,1.0

In [40]:
df_promoters.to_csv("dataframes/12_regulonDB_parsed_and_checked_locusTag_TF.csv", index=False)